name: Pylint

on: [push] # на какие действия(на пуш, на создание новой ветки, на создание нового тега)

jobs:
  build:

    runs-on: ubuntu-latest # пишем где у нас это выполняется

    steps:
    - uses: actions/checkout@v2 # выполняется чекаут, ставится текущее состояние репозитория
    - name: Set up Python 3.8 # ставится питон 3.8
      uses: actions/setup-python@v1 #
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
